version: '3'

services:
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        command: --smallfiles --bind_ip_all
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMINUSERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMINPASSWORD}
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ADMINUSERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ADMINPASSWORD}
            MONGO_INITDB_DATABASE: backoffice
        volumes:
            - ./mongo/db:/data/db:delegated
            - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js
        expose:
            - ${MONGODB_PORT}

    client:
        container_name: client
        build: ./client
        expose:
            - ${CLIENT_APP_PORT}
        volumes:
            - ./client:/var/client:cached
            - '/var/client/node_modules'
        links:
            - server

    server:
        container_name: server
        build: ./server
        expose:
            - ${SERVER_APP_PORT}
        volumes:
            - ./server:/var/server:cached
            - '/var/server/node_modules'
        links:
            - mongo

    proxy:
        container_name: proxy
        image: abiosoft/caddy
        ports:
            - '80:80'
            - '443:443'
            - '8080:8080'
        links:
            - client
            - server
        volumes:
            - './Caddyfile:/etc/Caddyfile'
            - './.caddy:/root/.caddy'
