version: '3'

services:
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        command: --smallfiles --bind_ip_all
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ADMINUSERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ADMINPASSWORD}
            MONGO_INITDB_DATABASE: backoffice
        volumes:
            - ./mongo/db:/data/db:delegated
            - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js
        expose:
            - ${MONGODB_PORT}

    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile.prod
        expose:
            - ${CLIENT_APP_PORT}
        links:
            - server

    server:
        container_name: server
        restart: always
        build:
            context: ./server
            dockerfile: Dockerfile.prod
        expose:
            - ${SERVER_APP_PORT}
        links:
            - mongo
        env_file: .env

    proxy:
        container_name: proxy
        image: abiosoft/caddy
        ports:
            - '80:80'
            - '443:443'
            - '8080:8080'
        links:
            - client
            - server
        volumes:
            - './Caddyfile.prod:/etc/Caddyfile'
            - './.caddy:/root/.caddy'
